### ISSUE TITLE
Spreedly.create(SpreedlyCreditCard) marshalling annotations

### ISSUE THREAD

**Issue by jmswenski** [rjstanford/spreedly-java#3]
If you try to use Spreedly.create(SpreedlyCreditCard), the library blows up with a marshaling exception because there are some missing XML root node annotations on the underlying request models. 

I created a pull request that puts them in. Let me know if you want to me to base it off of master or if there is a different method you want to use incorporate changes

**Comment by rjstanford** [comment]
I'll run it through this evening when I'm at the computer and do a merge and a release. We just ran into this - amazingly we'd never taken a server-side card until just this week when we had to do some data import. I thought we had it fixed though so I'll get it out and released this weekend.

**Comment by jmswenski** [comment]
Yeah, that makes sense for PCI reasons that it's a lesser used function. Our situation is _exactly_ the same where we don't use that method server side but we needed to build a tool to do some imports for a migration.

**Comment by jmswenski** [comment]
I also noticed that my PR failed the integration tests, let me know if that's expected or something I need to fix.

**Comment by jmswenski** [comment]
PR merged. Closing.
